apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-kind-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /demo-kind(/|$)(.*)
        backend:
          service:
            name: demo-kind
            port:
              number: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: demo-kind
  labels:
    app: demo-kind
spec:
  type: ClusterIP
  selector:
    app: demo-kind
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-kind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kind
  template:
    metadata:
      labels:
        app: demo-kind
        version: v1
    spec:
      containers:
      - name: demo-kind
        image: solmedia/demo-kind
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
