kind: Service
apiVersion: v1
metadata:
  name: demo-minikube
  labels:
    app: demo-minikube
spec:
  type: NodePort
  selector:
    app: demo-minikube
  ports:
  - port: 38080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-minikube
  template:
    metadata:
      labels:
        app: demo-minikube
        version: v1
    spec:
      containers:
      - name: demo-minikube
        image: solmedia/demo-minikube
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
